packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  msw: true
minimumReleaseAge: 0 # не выпускаем версии меньше 0 дней
